height = input("Please Enter your Height in Meters ")
weight = input("Please enter your weight in KG ")
print(type(height))
print(type(weight))
height=float(height)
weight=float(weight)
print(type(height))
print(type(weight))
# print(height+)
BMI=weight/(height*height)
BMI=int(BMI)
print("Total BMI is ", BMI)